http {
    server {
        listen 9000;
        server_name localhost;
        root www;
        index index.html index.htm;
        client_max_body_size 10485760;

        error_page 400 /error_pages/400.html;
        error_page 403 /error_pages/403.html;
        error_page 404 /error_pages/404.html;
        error_page 405 /error_pages/405.html;
        error_page 413 /error_pages/413.html;
        error_page 500 /error_pages/500.html;
        error_page 502 /error_pages/502.html;
        error_page 503 /error_pages/503.html;

        location / {
            root ./www;
            limit_except GET POST;
            autoindex off;
        }

        location /uploads {
            root ./www/uploads;
            limit_except GET POST DELETE;
            upload_enable on;
            upload_store ./www/uploads;
            autoindex on;
        }

        location /cgi-bin {
            root ./www/cgi-bin;
            limit_except GET POST;
            cgi_pass .php /usr/bin/php-cgi;
            cgi_pass .py /usr/bin/python3;
        }
    }

    server {
        listen 8000;
        server_name test;
        root ./www;
        index index.html;

        location / {
            root ./www;
            limit_except GET;
            autoindex on;
        }
    }
}
