http {
    server {
        listen eighty;
        server_name localhost;
        root /var/www/html;
        index;
        location / {
            root;
            index;
            limit_except FOO;
        }
        listen 9090;
    }
    location /bad {
        root /tmp;
    }
}